const CA_DL={id:"ca_dl",title:"California DL / ID",color:"#2563EB",subtitle:"Gen 3: 2018–Sep 2025 · Gen 4: Oct 2025–present",
sources:["CA DMV Press Release Oct 1 2025","CA DMV REAL ID Press Release Jan 22 2018","AAMVA DL/ID Card Design Standard 2020","NTSI State DL Format Guide","IDScan.net — 2025 CA DL Analysis","CA OLIN 2025-09"],
sections:[
{id:"S1",title:"Generation identification",hints:[["S1.1","Background shows redwood forest, poppies, Pacific coastline?","Yes → Gen 4 (Oct 2025+)","CONTEXT"],["S1.2","Background shows Gold Rush miner on right + poppies lower left?","Yes → Gen 3 (2018–Sep 2025)","CONTEXT"],["S1.3","Back of card has a magnetic strip?","Gen 3: Yes. Gen 4: No.","CONTEXT"],["S1.4","Back has TWO distinct barcodes?","Gen 4 only — second barcode carries digital signature","CONTEXT"]]},
{id:"S2",title:"Card orientation & layout",hints:[["S2.1","Card is in HORIZONTAL (landscape) orientation?","Required for holders age 21+","YES"],["S2.2","If cardholder under 21 by DOB: card is VERTICAL (portrait)?","Under-21 CA DL/ID must be vertical since 2010","YES"],["S2.3","On horizontal card (21+): primary photo on LEFT side?","Photo always left for 21+ horizontal cards","YES"]]},
{id:"S3",title:"Header & document type color",hints:[["S3.1","Card header reads 'CALIFORNIA' or 'California' at top?","All CA DL/IDs display state name in header","YES"],["S3.2","If Driver License: card type text appears in BLUE?","CA DMV (2018+): driver license type = blue","YES"],["S3.3","If Identification Card: card type text appears in GREEN?","CA DMV (2018+): ID card type = green","YES"],["S3.4","Label says exactly 'DRIVER LICENSE' (not 'DRIVER'S LICENSE')?","Official label omits apostrophe","YES"]]},
{id:"S4",title:"REAL ID & federal compliance",hints:[["S4.1","Gold bear silhouette with white star inside in upper area?","REAL ID–compliant cards since Jan 22, 2018","YES"],["S4.2","If no bear+star: 'FEDERAL LIMITS APPLY' near top?","Non-REAL ID must show this text","CONTEXT"],["S4.3","Both bear+star AND 'FEDERAL LIMITS APPLY' absent on post-Jan 2018 card?","Either must appear post-Jan 2018. Both absent = red flag","NO"]]},
{id:"S5",title:"Name field format",hints:[["S5.1","Last name on FIRST line of name field?","CA DL: Line 1 = last name; Line 2 = first + middle","YES"],["S5.2","First/middle name on SECOND line?",null,"YES"],["S5.3","All name characters in UPPERCASE?","AAMVA standard requires uppercase names","YES"],["S5.4","Name contains only Latin chars, hyphens, or apostrophes?",null,"YES"]]},
{id:"S6",title:"License / ID number format",hints:[["S6.1","DL/ID number = ONE uppercase letter + SEVEN digits (e.g. A1234567)?","CA format: 1 alpha + 7 numeric = 8 chars total","YES"],["S6.2","DL/ID number free of spaces, hyphens, or special characters?",null,"YES"],["S6.3","DL/ID number on front matches barcode field DAQ?","Mismatch = tampering indicator","YES"]]},
{id:"S7",title:"Date fields — format and logic",hints:[["S7.1","All dates (DOB, ISS, EXP) in MM/DD/YYYY format?","CA DL uses MM/DD/YYYY consistently","YES"],["S7.2","Issue date (ISS) strictly before expiration (EXP)?","ISS >= EXP is logically impossible","YES"],["S7.3","EXP approximately 5 years after ISS?","Standard CA DL renewal cycle is 5 years","YES"],["S7.4","DOB predates ISS by at least 16 years?","Minimum driving age in CA is 16","YES"],["S7.5","DOB on front consistent with barcode field DBB?","DOB mismatch face vs barcode = tampering","YES"]]},
{id:"S8",title:"Physical descriptor fields",hints:[["S8.1","Eye color (EYES) is 3-letter AAMVA code: BRN, BLU, GRN, HZL, GRY, BLK?","Full words like 'brown' are non-standard","YES"],["S8.2","Height (HGT) in feet-inches format (e.g. 5-09 or 5'09\")?","CA DL uses imperial format","YES"],["S8.3","Sex (SEX) is single character: M, F, or X?","CA allows M, F, X (non-binary) since 2019","YES"],["S8.4","Weight (WGT) physically plausible for listed height?","Extreme values (e.g. 115 lb for 6'1\") are a flag","YES"]]},
{id:"S9",title:"Under-21 markers",hints:[["S9.1","If under 21: RED BAR with 'AGE 21 IN [YEAR]'?","Required for 18–20 year old holders","YES"],["S9.2","If under 18: BLUE BAR with 'PROVISIONAL UNTIL AGE 18 IN [YEAR]'?",null,"YES"],["S9.3","Year in age bar matches year cardholder turns 21 by DOB?","Year mismatch = semantic red flag","YES"]]},
{id:"S10",title:"Security features — visual",hints:[["S10.1","Smaller grayscale ghost photo visible on card face?","Laser-engraved ghost photo is a CA security feature","YES"],["S10.2","DOB printed ACROSS primary photo in raised 3D numerals?","3D tactile DOB over photo is CA-specific","YES"],["S10.3","Holographic overlay shifts color/imagery at different angles?","All CA DL/IDs have holographic laminate since 2010","YES"],["S10.4","Hologram shows CA-themed imagery (bear, state seal) that shifts when tilted?","Generic holograms suggest counterfeit overlay","YES"],["S10.5","Microprinting visible under magnification around photo or design?","Look for 'CA DMV' or 'VALID ID' text","YES"]]},
{id:"S11",title:"UV / ultraviolet features",hints:[["S11.1","Under UV light: full-color ghost image of cardholder appears?","Full-color UV ghost is a CA DL security feature","YES"],["S11.2","Under UV: additional patterns or text not seen under normal light?","Absence of UV elements = counterfeit indicator","YES"]]},
{id:"S12",title:"Laser perforation",hints:[["S12.1","When backlit: California brown bear outline visible through laser-perforated holes?","Laser perforation bear is CA-specific since 2010","YES"]]},
{id:"S13",title:"Back — barcodes & DD field",hints:[["S13.1","PDF417 (stacked 2D) barcode present on back?","AAMVA mandates PDF417. QR code = red flag","YES"],["S13.2","PDF417 clearly printed (no smearing/blur/pixelation)?","Poor quality is common in counterfeits","YES"],["S13.3","Barcode header begins with '@' then '636014' (CA AAMVA IIN)?","636014 = California's official issuer code","YES"],["S13.4","DD (Document Discriminator) field visible on back?","DD uniquely identifies each card issuance","YES"],["S13.5","DD in barcode (field DCF) matches DD printed on back?","Mismatch = data alteration indicator","YES"],["S13.6","On Gen 3 card: magnetic strip on back?","Gen 3 (2018–Sep 2025) should have strip","CONTEXT"],["S13.7","On Gen 4 card (Oct 2025+): back free of magnetic strip?","Gen 4 removed the magnetic strip","CONTEXT"]]},
{id:"S14",title:"Barcode cross-field consistency",hints:[["S14.1","Name in barcode DCS/DAC/DAD matches printed name on front?","Name mismatch = definitive tampering indicator","YES"],["S14.2","Sex code in barcode DBC matches SEX field? (1=M, 2=F, 9=X)",null,"YES"],["S14.3","Eye color in barcode DAY matches EYES field on front?",null,"YES"],["S14.4","Height in barcode DAU matches HGT field on front?",null,"YES"],["S14.5","License number in barcode DAQ matches DL/ID number on front?",null,"YES"],["S14.6","Expiration in barcode DBA matches EXP date on front?",null,"YES"],["S14.7","Issue date in barcode DBD matches ISS date on front?",null,"YES"],["S14.8","Address in barcode DAG/DAI/DAJ/DAK matches front? State (DAJ) = 'CA'?",null,"YES"]]},
]};

export default CA_DL;
