const DEU_ID={id:"deu_id",title:"German ID (Personalausweis)",color:"#B91C1C",subtitle:"Gen 2010 · Gen 2021 (Aug 2021) · Gen 2024 (May 2024)",
sources:[
  "BSI — German ID Cards (bsi.bund.de)",
  "Personalausweisportal.de — Federal Official Portal",
  "Wikipedia — German Identity Card (en.wikipedia.org / Grokipedia)",
  "Keesing Technologies — German ID 2021 Model Infographic (Oct 2021)",
  "Regula Forensics — German Passport & ID Cards (Nov 2025)",
  "TrustDocHub — Verify German ID Card (Feb 2026)",
  "Bundesdruckerei — Alphanumeric Serial Number Specification",
  "second.wiki — Ausweisnummer (ID number format)",
  "EU Regulation 2019/1157 — Security of EU Identity Cards",
  "ICAO Doc 9303 Part 5 — TD1 MRZ Specification",
],
sections:[
{id:"G",title:"Generation identification",hints:[
  ["G.1","EU flag with 'DE' in white text visible on front (upper-left area)?","Gen 2021+ (version 2108+): mandatory per EU Reg 2019/1157. Gen 2010–2017: EU flag absent or no 'DE' text.","CONTEXT"],
  ["G.2","Signature field is ABSENT from the front of the card?","Gen 2021+: signature eliminated. Gen 2010–2017: signature field is present.","CONTEXT"],
  ["G.3","Optically variable (color-shifting) stripe visible on the back of the card?","Gen 2021+ exclusive feature — not present on earlier generations.","CONTEXT"],
  ["G.4","Photo appears fused/integrated into the card material with a smooth surface (no visible edge or lift)?","Innosec Fusion® system (Gen 2021+) integrates photo into polycarbonate. Raised edge, gap, or removable photo = older gen or counterfeit.","YES"],
  ["G.5","For cards issued Aug 2 2021 onward: version number '2108' or later visible in MRZ optional data field?","Gen 2021 = version 2108. Gen 2024 = version 2405. Pre-2021 cards: version absent from MRZ.","CONTEXT"],
]},
{id:"H",title:"Header & document identifier",hints:[
  ["H.1","Card displays 'PERSONALAUSWEIS' on the front?","Primary document type label on all post-2010 cards.","YES"],
  ["H.2","Card displays 'BUNDESREPUBLIK DEUTSCHLAND' on the front?","All post-2010 cards carry the issuing state name.","YES"],
  ["H.3","Federal Eagle (Bundesadler) logo is visible on the front?","All post-2010 German ID cards carry the Bundesadler.","YES"],
  ["H.4","Card is in HORIZONTAL (landscape) orientation?","All current German PA cards are ID-1 format, horizontal.","YES"],
  ["H.5","Card is credit-card size (approx. 85.6 × 54 mm)?","ID-1 format since Nov 2010. Larger format = pre-2010 old generation.","YES"],
]},
{id:"N",title:"Name fields",hints:[
  ["N.1","Surname (Familienname) appears in the labeled surname field?","Field is labeled 'Familienname' or 'Name'. Must be filled.","YES"],
  ["N.2","Given name(s) (Vornamen) appear in the labeled given-name field?","Field is labeled 'Vornamen'. Multiple given names separated by space.","YES"],
  ["N.3","Printed name may contain German umlauts (ä, ö, ü) or ß?","These are legitimate German characters in the visual inspection zone. Their presence is normal, not a red flag.","CONTEXT"],
  ["N.4","In MRZ Line 3, umlauts transliterated: ä→AE or A, ö→OE or O, ü→UE or U, ß→SS?","Both AE and A are valid for ä (same person may have MUELLER or MULLER in different docs — both valid). Source: ICAO Doc 9303 Part 3; Regula Forensics Nov 2025.","YES"],
  ["N.5","Academic title (Dr.) may appear next to surname on front (Gen 2010–2023) or on back (Gen 2024+)?","Doctorate title is a valid field. Gen 2024 (version 2405) moved it to back.","CONTEXT"],
]},
{id:"D",title:"Document number (Seriennummer)",hints:[
  ["D.1","Document number on card face is exactly 9 alphanumeric characters?","Post-Nov 2010: 9-char serial number on card face. Check digit appears in MRZ only. Source: Bundesdruckerei serial number spec.","YES"],
  ["D.2","First character of document number is from: L, M, N, P, R, T, V, W, X, Y?","Only these 10 letters are valid as the first character. Source: Bundesdruckerei alphanumeric PA serial number specification.","YES"],
  ["D.3","Remaining 8 characters are from digits (0–9) or letters C, F, G, H, J, K, L, M, N, P, R, T, V, W, X, Y, Z?","27 valid characters total (10 digits + 17 consonants). Vowels and B/D/Q/S are excluded by design.","YES"],
  ["D.4","Document number contains NO vowels (A, E, I, O, U) at any position?","Vowels are excluded to prevent meaningful words. Their presence = forgery indicator.","YES"],
  ["D.5","Document number contains NO letters B, D, Q, or S at any position?","These letters excluded for machine-readability and confusion-avoidance. Their presence = forgery indicator.","YES"],
]},
{id:"C",title:"CAN — Card Access Number",hints:[
  ["C.1","A 6-digit CAN (Card Access Number) is visible on the front of the card?","CAN is printed on card front; used to initiate PACE-protected RFID chip reading. Required on all PA cards.","YES"],
  ["C.2","CAN consists of exactly 6 numeric digits (no letters, no spaces)?","Strictly 6-digit numeric per ICAO PACE protocol and BSI specification.","YES"],
]},
{id:"V",title:"Validity and dates",hints:[
  ["V.1","All printed dates are in DD.MM.YYYY format (European dot-separated)?","Germany uses DD.MM.YYYY universally. US-style MM/DD/YYYY or ISO YYYY-MM-DD = forgery indicator.","YES"],
  ["V.2","Validity period is approximately 10 years from issue date (cardholder aged 24+ at time of issue)?","Adults (24+): 10-year validity. Source: Personalausweisgesetz §28; BSI; Wikipedia.","YES"],
  ["V.3","Validity period is approximately 6 years from issue date (cardholder under 24 at time of issue)?","Under-24 at issuance: 6-year validity. Age at ISSUE TIME determines period, not current age.","YES"],
  ["V.4","Expiry date equals issue date + expected validity period (10 or 6 years)?","Any other interval without documented special reason = anomalous.","YES"],
  ["V.5","Card has not expired (expiry date is in the future)?","Expired German PA is no longer valid. There is NO extension mechanism (unlike US Green Cards). Expired = invalid document.","YES"],
]},
{id:"B",title:"Back of card — personal data fields",hints:[
  ["B.1","Height (Größe) is expressed in centimeters (cm), e.g. '175 cm' or '1,75 m'?","Germany uses metric. Imperial format (feet/inches) = non-standard, forgery indicator.","YES"],
  ["B.2","Eye color (Augenfarbe) is in German: blau, braun, grau, grün, haselnussbraun, schwarz, violett, or 'nicht feststellbar'?","Only these German terms are used on genuine cards. English terms (blue, brown, etc.) = non-standard.","YES"],
  ["B.3","Issuing authority (Ausstellungsbehörde) is a German municipal/civil authority name?","Examples: 'Stadt München', 'Bürgeramt Hamburg', 'Landkreis Freising'. Non-German authority = non-standard.","YES"],
  ["B.4","Date of issue (Ausgestellt am) is present in DD.MM.YYYY format?",null,"YES"],
  ["B.5","Address (Anschrift) is present on the back? (May be outdated if holder moved — this is normal and legal)","German PA is NOT reissued when holder moves. Outdated address ≠ forgery. Address stickers may be used.","CONTEXT"],
  ["B.6","MRZ is positioned along the BOTTOM edge of the back of the card?","BSI specification: MRZ is at lower edge of back. MRZ on front = non-standard.","YES"],
]},
{id:"M",title:"MRZ — machine readable zone (back)",hints:[
  ["M.1","Back displays exactly THREE lines of text, each approximately 30 characters wide?","TD1 format: 3 × 30 chars. Used by German PA since Nov 2010. Two-line MRZ = wrong document type.","YES"],
  ["M.2","MRZ Line 1 begins with 'IDD<<' (doc type 'ID' + Germany's unique 1-letter code 'D' + fillers)?","Germany is the ONLY ICAO-recognized country using a 1-letter country code ('D') in the MRZ. All other nations use 3-letter codes. 'IDDEUT' or 'IDDEU' would be wrong. Source: Regula Forensics Nov 2025.","YES"],
  ["M.3","Positions 6–14 of MRZ Line 1 contain the 9-character document number?","Document number occupies exactly 9 characters starting at position 6 of Line 1.","YES"],
  ["M.4","Position 15 of MRZ Line 1 is the check digit for the document number (ICAO 7-3-1 algorithm)?","Check digit computed from the 9-char document number using ICAO weighting 7, 3, 1, 7, 3, 1…","YES"],
  ["M.5","Positions 16–30 of MRZ Line 1 are all filler characters '<<'?","No optional data in Line 1 for German PA. All 15 trailing chars = '<<<<<<<<<<<<<<<'.","YES"],
  ["M.6","MRZ Line 2, positions 1–6: DOB in YYMMDD format?","2-digit year (e.g., '850320' = 20 March 1985).","YES"],
  ["M.7","MRZ Line 2, position 7: DOB check digit (ICAO 7-3-1 algorithm)?",null,"YES"],
  ["M.8","MRZ Line 2, position 8: sex character M, F, or < (not full words)?","'<' = not specified. Full words like 'MALE' = non-standard.","YES"],
  ["M.9","MRZ Line 2, positions 9–14: expiry date in YYMMDD format?",null,"YES"],
  ["M.10","MRZ Line 2, position 15: expiry check digit?",null,"YES"],
  ["M.11","MRZ Line 2, positions 16–18: nationality code is 'D<<' (Germany's 1-letter nationality code)?","German citizens have nationality 'D<<' in MRZ. Non-German citizens cannot hold a German PA.","YES"],
  ["M.12","MRZ Line 2, positions 19–28: optional data contains issue date in YYMM format?","Issue date encoded as YYMM (4 chars) in the optional data field. Source: TrustDocHub; second.wiki.","YES"],
  ["M.13","MRZ Line 2, position 29: composite check digit (covering doc number, DOB, expiry, optional data)?","4 check digits total in German PA MRZ: doc number, DOB, expiry, and composite. Invalid composite = tampering.","YES"],
  ["M.14","MRZ Line 3 contains name in SURNAME<<GIVENNAME format?","Double '<<' separates primary (surname) from secondary (given name) identifiers. Spaces encoded as '<'.","YES"],
  ["M.15","Printed document number on front matches MRZ Line 1 positions 6–14?","Any mismatch = data tampering.","YES"],
  ["M.16","Printed DOB on front (DD.MM.YYYY) matches MRZ Line 2 DOB (YYMMDD, converted)?","DOB mismatch between face and MRZ = data manipulation.","YES"],
  ["M.17","Printed expiry date (Gültig bis) on front matches MRZ Line 2 expiry (YYMMDD, converted)?","Expiry mismatch = tampering indicator.","YES"],
]},
{id:"S",title:"Security features — visual",hints:[
  ["S.1","Identigram® hologram (DOVID) visible on front — complex shifting imagery when tilted?","Identigram® is Bundesdruckerei's proprietary Diffractive Optical Variable Image Device. Static or generic hologram = counterfeit.","YES"],
  ["S.2","CLI (Changeable Laser Image) visible — laser feature showing different images at different angles?","CLI is created by laser engraving. Present in Gen 2021+.","YES"],
  ["S.3","OVI (Optically Variable Ink) present — ink that visibly changes color at different viewing angles?","OVI color shift (e.g., gold-to-green) is difficult to reproduce with standard inkjet/laser printing.","YES"],
  ["S.4","Card is hard rigid polycarbonate (not flexible, not paper-like)?","All post-2010 German PA cards are solid polycarbonate. Any flexibility = counterfeit indicator.","YES"],
  ["S.5","Photo surface is flush with card (smooth, no raised edge, no visible gap or seam around photo)?","Innosec Fusion® fuses photo into polycarbonate. Any edge, gap, or peel-up potential = non-genuine.","YES"],
  ["S.6","Multi-color guillochés (intricate fine-line geometric background patterns) visible on front and back?","Guillochés produced by specialty Bundesdruckerei equipment not available to counterfeiters.","YES"],
  ["S.7","Under UV/black light, additional patterns, text, or luminescent designs appear on front and/or back?","Multiple UV-reactive colors on both sides (Gen 2021+). Complete absence of UV features = counterfeit.","YES"],
  ["S.8","Microprinting visible under magnification (fine text within guillochés or border elements)?","Bundesdruckerei microprinting is part of the genuine security design.","YES"],
  ["S.9","Contactless chip symbol (NFC/RFID icon) visible on front of card?","Chip symbol mandatory per EU Reg 2019/1157 on Gen 2021+ cards.","YES"],
]},
{id:"X",title:"Cross-field consistency",hints:[
  ["X.1","Document number on front matches document number in MRZ Line 1 (positions 6–14)?","Mismatch = definitive tampering.","YES"],
  ["X.2","Date of birth on front (DD.MM.YYYY) matches DOB in MRZ Line 2 (YYMMDD, converted)?",null,"YES"],
  ["X.3","Expiry date (Gültig bis) on front matches expiry in MRZ Line 2 (YYMMDD, converted)?",null,"YES"],
  ["X.4","Validity period is consistent with cardholder's age at issue date (10 yrs for 24+; 6 yrs for under-24)?","Check: does (expiry – issue) match the expected period given DOB and issue date?","YES"],
  ["X.5","Nationality field shows 'DEUTSCH' on printed card AND 'D<<' in MRZ nationality field?","Only German citizens hold a Personalausweis. Non-German nationals hold an Aufenthaltstitel instead.","YES"],
  ["X.6","Printed name matches MRZ Line 3 name (accounting for umlaut transliteration)?","ä→AE or A, ö→OE or O, ü→UE or U, ß→SS. Discrepancy beyond valid transliteration = tampering.","YES"],
  ["X.7","Generation features are internally consistent (EU flag+DE ↔ no signature ↔ OV stripe on back)?","A card with EU+DE flag but a signature field, or OV stripe but no CLI = hybrid/mixed generation forgery.","YES"],
  ["X.8","All 4 MRZ check digits compute correctly using ICAO 7-3-1 algorithm?","Invalid check digit(s) = data was altered after the genuine MRZ was printed.","YES"],
]},
]};

export default DEU_ID;
