const US_PR={id:"us_greencard",title:"US Green Card (I-551)",color:"#059669",subtitle:"Gen 2010 · Gen 2017 · Gen 2023",
sources:["USCIS Press Releases: May 2010, May 2017, Jan 30 2023","USCIS I-9 Central — List A Documents","E-Verify Guidance Jan 2023","NY OTDA GIS 17DC018 & 23DC018","ICAO Doc 9303 Part 5 — TD1 MRZ","i-9intelligence.com I-551 Field Guide"],
sections:[
{id:"G",title:"Generation identification",hints:[["G.1","Card displays Statue of Liberty imagery on front?","Gen 2017 & 2023: SoL artwork. Gen 2010: flag/map motif","CONTEXT"],["G.2","Overall card color scheme predominantly green?","All Gen 2010+ cards are green","YES"],["G.3","Photo on BOTH front AND back?","Gen 2017 & 2023: both sides required","YES"],["G.4","Laser-engraved fingerprint visible on front?","Gen 2010 & 2017: Yes. Gen 2023: REMOVED","CONTEXT"],["G.5","Signature field on card?","Gen 2010: optional. Gen 2017+: ELIMINATED","CONTEXT"],["G.6","Back has optical or magnetic stripe?","Gen 2010: Yes. Gen 2017+: REMOVED","CONTEXT"],["G.7","Back photo box has partial transparent window / layer-reveal?","Exclusive to Gen 2023","CONTEXT"]]},
{id:"H",title:"Header & document identifier",hints:[["H.1","Card displays 'PERMANENT RESIDENT' prominently on front?",null,"YES"],["H.2","'UNITED STATES OF AMERICA' appears on card?","'USA' alone = non-standard","YES"],["H.3","'FORM I-551' appears on back (typically top-left)?","All current-era cards carry this on back","YES"]]},
{id:"A",title:"A-Number / USCIS number",hints:[["A.1","A-Number visible on front, labeled 'USCIS#' or 'A#'?","Gen 2017+: labeled 'USCIS#'. Older: 'A#'. Unlabeled = non-standard","YES"],["A.2","A-Number is 7–9 digits (optionally preceded by 'A-' or 'A')?","NOT 11 digits (that is an I-94 number)","YES"],["A.3","A-Number free of letters other than optional leading 'A'?","Numeric portion must be all digits","YES"]]},
{id:"F",title:"Name fields",hints:[["F.1","Cardholder's name in UPPERCASE?",null,"YES"],["F.2","Surname clearly labeled or listed first?",null,"YES"],["F.3","Name contains only standard Latin chars, spaces, or hyphens?","Non-Latin chars should not appear","YES"]]},
{id:"D",title:"Date fields and validity logic",hints:[["D.1","All dates (DOB, Card Expires, Resident Since) in consistent format?","Mixed formats on same card = fabrication indicator","YES"],["D.2","If non-CR category: CARD EXPIRES ~10 years after RESIDENT SINCE?","Standard non-conditional: 10-year validity","YES"],["D.3","If CR category: CARD EXPIRES ~2 years after RESIDENT SINCE?","Conditional (CR) cards: 2-year validity","YES"],["D.4","RESIDENT SINCE before or equal to CARD EXPIRES?",null,"YES"],["D.5","CARD EXPIRES uses 4-digit year (e.g. 2029 not 29)?","Genuine USCIS cards use 4-digit years","YES"],["D.6","DOB at least 14 years before RESIDENT SINCE?",null,"YES"]]},
{id:"C",title:"Category code — semantic consistency",hints:[["C.1","Category code is 2–3 chars with letter prefix + digit suffix (e.g. IR1, CR1, E51)?","'EB5' NOT valid — correct EB-5 codes are E51, E52, E53","YES"],["C.2","Category begins with recognized USCIS prefix: IR, CR, CF, IB, IW, F, E, DV, RE, SB, AM?",null,"YES"],["C.3","If CR category: CARD EXPIRES shows ~2-year window?","CR + 10-year expiry = structural contradiction","YES"],["C.4","If non-CR category: CARD EXPIRES shows ~10-year window?","All standard PR categories get 10-year cards","YES"]]},
{id:"N",title:"Document number (back of card)",hints:[["N.1","13-character alphanumeric document number visible on back or in MRZ?","All Gen 2010+ cards carry a 13-char doc number","YES"],["N.2","First 3 chars are letters only (e.g. MSC, VSC, LIN, SRC, WAC, NBC, IOE)?","Identifies the USCIS service center","YES"],["N.3","Chars 4–5 represent plausible 2-digit USCIS fiscal year (10–26)?","FY runs Oct 1 – Sep 30","YES"],["N.4","Chars 6–8 are three digits for a workday (001–260)?","Codes 000 or 999 = anomalous","YES"],["N.5","Final 5 chars (positions 9–13) are all digits?","Last 5 = unique case sequence, must be numeric","YES"]]},
{id:"M",title:"MRZ — machine readable zone (back)",hints:[["M.1","Back displays exactly THREE lines of ~30 chars each?","US green card MRZ is TD1: 3×30. Two-line = wrong type","YES"],["M.2","MRZ Line 1 begins with 'C1USA' or 'C2USA'?","C1 = full-time US PR; C2 = commuter LPR","YES"],["M.3","A-Number in MRZ Line 1 (positions 6–14) matches USCIS# on front?","Mismatch = data manipulation","YES"],["M.4","Last 13 chars of MRZ Line 1 match 13-char document number on back?",null,"YES"],["M.5","DOB in MRZ Line 2 (YYMMDD) matches DOB on front?",null,"YES"],["M.6","Sex char in MRZ Line 2 matches sex field on front (M, F, or X)?",null,"YES"],["M.7","Expiry in MRZ Line 2 (YYMMDD) matches CARD EXPIRES on front?",null,"YES"],["M.8","MRZ Line 3 contains name in SURNAME<<GIVENNAME format?","Double '<<' separates surname from given names","YES"],["M.9","Name in MRZ Line 3 corresponds to printed name on front?",null,"YES"]]},
{id:"P",title:"Photo consistency",hints:[["P.1","On Gen 2017 or 2023: second photo visible on BACK of card?","Missing back photo on Gen 2017+ = forgery indicator","YES"],["P.2","Front photo consistent (same person, similar age) with back photo?","Substitution on one side = common forgery","YES"],["P.3","Photo consistent with sex and name indicated on card?","Male photo + female name (or vice versa) = major red flag","YES"]]},
{id:"S",title:"Security features — visual",hints:[["S.1","Holographic overlay shifts or shows different imagery when tilted?","All Gen 2010+ cards have holographic elements","YES"],["S.2","Optically variable ink (OVI) changes color at different angles?","OVI present Gen 2017+, enhanced in Gen 2023","YES"],["S.3","Tactile (raised) printing present and integrated with card artwork?","Gen 2023: tactile printing integrated with artwork","YES"],["S.4","Card appears constructed of hard plastic/polycarbonate (not flexible)?","All modern USCIS green cards are hard polycarbonate","YES"],["S.5","Under UV light: additional patterns, text, or images become visible?","Complete absence of UV elements = counterfeit indicator","YES"]]},
{id:"X",title:"Cross-field consistency",hints:[["X.1","Name on front matches name in MRZ Line 3?",null,"YES"],["X.2","DOB on front matches DOB in MRZ Line 2?",null,"YES"],["X.3","A-Number on front matches A-Number in MRZ Line 1?",null,"YES"],["X.4","Expiry date on front matches expiry in MRZ Line 2?",null,"YES"],["X.5","Category code consistent with validity period? (CR=2 yrs; others=10 yrs)","Most commonly fabricated mismatch","YES"],["X.6","If back photo present: depicts same individual as front photo?",null,"YES"],["X.7","Given name consistent with sex field? (female name should not appear with Sex=M)","Name/sex contradiction = major fabrication indicator","YES"],["X.8","Service center code (first 3 letters of doc number) is recognized USCIS code?","Valid: MSC, VSC, LIN, SRC, WAC, NBC, IOE","YES"]]},
{id:"E",title:"Expiry and special status",hints:[["E.1","CARD EXPIRES date present on card?","Most cards have expiry. No-expiry = very old but may be valid","CONTEXT"],["E.2","If expired: Form I-797 receipt notice extends validity?","I-751/I-829 filers may have 48-month extension","CONTEXT"],["E.3","If expired with no I-797: expiry passed by more than 48 months?","Over 48 months without extension = very likely invalid","NO"]]},
]};

export default US_PR;
